#!/bin/sh
echo "*************************************"
echo "* Oscam_libusb_lc installiert!      *"
echo "* Oscam_libusb_lc kann nun im       *"
echo "* CI/Softcam-Menue gestartet werden *"
echo "*************************************"
exit 0
