#!/bin/sh

echo "Halte Softcams und Cardserver an!"

/etc/init.d/softcam stop

/etc/init.d/cardserver stop

	SOFTCAMLINK=`readlink -f /etc/init.d/softcam`
	CARDSERVERLINK=`readlink -f /etc/init.d/cardserver
	if [ "${SOFTCAMLINK}" == "/etc/init.d/softcam.OScam-Dmod" ]
	then
		ln -sf /etc/init.d/softcam.None /etc/init.d/softcam
	fi
	CARDSERVERLINK=`readlink -f /etc/init.d/cardserver
	if [ "${SOFTCAMLINK}" == "/etc/init.d/cardserver.OScam-Dmod" ]
	then
		ln -sf /etc/init.d/cardserver.None /etc/init.d/cardserver
	fi

