#!/bin/sh
echo "*************************************"
echo "* Oscam installiert!                *"
echo "* Oscam kann nun im                 *"
echo "* CI/Softcam-Menue gestartet werden *"
echo "*************************************"
exit 0
