#!/bin/sh
echo "Deinstalliere Oscam ..."
/etc/init.d/cardserver stop
/etc/init.d/softcam stop
sleep 5
ln -sf /etc/init.d/softcam.None /etc/init.d/softcam
ln -sf /etc/init.d/cardserver.None /etc/init.d/cardserver
exit 0
